### ISSUE TITLE
Request available datasets

### ISSUE THREAD

**Issue by ZhiyangZhou24** [pairlab/TranspareNet#2]
This is a great job. Thank you very much for your open source code and datasets. But when I downloaded datasets(URL: [https://borealisdata.ca/dataset.xhtml?persistentId=doi:10.5683/SP3/ZJJAJ3] I was too slow to download them successfully. Can you provide a more convenient way to download datasets？Thanks~

**Comment by ZhiyangZhou24** [comment]
I have solved this problem~

**Comment by Jaywen1** [comment]
请问您有用TODD数据集跑过别的深度恢复模型吗，我试了这个数据集，但是效果都不太理想

**Comment by Jaywen1** [comment]
请问您有用TODD数据集跑过别的深度恢复模型吗，我试了几个模型，但是效果都不太理想
